### ISSUE TITLE
用的是demo3里面的第二个方法。

### ISSUE THREAD

**Issue by weizhangCoder** [Phelthas/TEST_XMLCommon#1]
当我这个界面有MJ刷新的时候，会被挡住有没有什么办法 啊。

**Comment by Phelthas** [comment]
你好 @weizhangCoder 
这个看你想要什么效果，我记得MJ应该是把mj_header insert到tableView.superView上的，
所以如果你想让mj_header出现在自己的headerView的下面的话，在KVO的回调中加个判断，让偏移量大于mj_header的高度时，headerView再跟着移动，否则就不移动，应该就可以实现；
如果你想让mj_header出现在自己的headerView的上面，就像这个headerView是tableViewHeader一样的话，那就稍微麻烦一点，你得看看mj_header有没有提供移动mj_header位置的方法，如果有就好说，没有的话就比较坑了，要么你就改mj的库，要么就自己写一个专门的针对这种情况的下拉刷新的控件

**Comment by weizhangCoder** [comment]
谢谢找到一个    _tableView.mj_header.ignoredScrollViewContentInsetTop = 150属性
